### ISSUE TITLE
Adding a theme not in the picklist stops the picklist being a selection

### ISSUE THREAD

**Issue by Metaduck** [idn-au/idn-metadata-creator#12]
![image](https://user-images.githubusercontent.com/5697354/236754290-e02c1f31-144b-413b-ac5a-876240fc37be.png)

If you add a term in the Theme field, it allows other terms in the vocabulary which is a way to add a keyword under the theme keyword BUT I think this is not what Nick means to happen. I will need to talk to him again about the use of the DCAT Theme

**Comment by jamiefeiss** [comment]
For the time being I've disabled the ability to add custom themes. Selecting multiple built-in themes works fine.
