### ISSUE TITLE
Agents Drop down showing duplicated items.

### ISSUE THREAD

**Issue by lalewis1** [idn-au/idn-metadata-creator#20]
Eg. When searching for Len Smith. 4 entries are shown. all with the same id. so selecting one selects them all.

I believe this is because the sparql query is malformed. it is not returning distinct agents as it should.

https://github.com/idn-au/idn-metadata-creator/blob/1c2105b72b779a5018b1d6fcd881985933e937a2/src/components/MetadataForm.vue#L1157

also the sdo:Organisation class is unneccessarily repeated.

@jamiefeiss If you give me access to the reopsitory I can try to amend and submit a PR.

**Comment by lalewis1** [comment]
Actually. scratch that. I think the query is OK, its just that Len Smith was defined as a person and an organisation so he was coming up multiple times.

Perhaps all that is needed is to just add in extra info in the drop down so that similar / same label entries can be differentiated.

**Comment by jamiefeiss** [comment]
@lalewis1 I've invited you to have write access to this repo. Btw the duplicated Organisation values are because I found typos in the data using both "Organisation" and "Organization" - spelt with "z" or "s". If that's no longer an issue then I'm happy for the query to be updated. Thanks

**Comment by lalewis1** [comment]
looks like there are no occurences of organisation with an 's' anymore. so probably safe to remove.

**Comment by lalewis1** [comment]
Actually, Do you think it is better to handle language tags in the front end instead of stripping them out, as it may be likely that we will want to display things in different languages, especially indigenous languages.

**Comment by lalewis1** [comment]
As discussed in the IDN meeting this morning [2024-06-025] We can proceed with stripping out the language tags.

**Comment by lalewis1** [comment]
fixed in #21
