### ISSUE TITLE
rdf licences with incorrect uri

### ISSUE THREAD

**Issue by lalewis1** [idn-au/idn-metadata-creator#22]
met tool generates incorrect namespace for rdflicenses.

example:

![image](https://github.com/idn-au/idn-metadata-creator/assets/151585421/ad9aad67-4eb4-47f2-97e8-0decc2024f33)

Should be http: not https:

**Comment by jamiefeiss** [comment]
Fixed in https://github.com/idn-au/vocab-data/pull/22
