### ISSUE TITLE
Consistency in determining Agent Information is required

### ISSUE THREAD

**Issue by Metaduck** [idn-au/idn-metadata-creator#8]
The Agent Information tab has a red cross which indicates that the fields are required but for consistency with other tabs, is it possible to also put a red asterixis against both Agent and Role?

**Comment by Metaduck** [comment]
Sorry - I cleared the page again and the Agent Information does NOT have a red cross before completion so needs to as well.

**Comment by jamiefeiss** [comment]
Resolved in 4cba653.
